Full_Stack/django/todo_project/todosite/todo_app/urls.py
from django.urls import path
from . import views

app_name = 'todo_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/<int:todo_id>', views.delete, name='delete'),
    path('markdone/<int:todo_id>', views.markdone, name='markdone'),
]

Full_Stack/django/todo_project/todosite/todosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todo_app.urls')),
    path('admin/', admin.site.urls),
]

Full_Stack/django/todo_project/todosite/todo_app/models.py
from django.db import models
from datetime import datetime


# Create your models here.
class Todo(models.Model):
    todo_text = models.CharField(max_length=200, unique=True)
    completed = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return self.todo_text

Full_Stack/django/todo_project/todosite/todo_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Todo


# Create your views here.
def index(request):
    todo_list = Todo.objects.all().order_by('-created_date')
    context = {'todos': todo_list}  # gets sent to index.html
    return render(request, 'todo_app/index.html', context)


def add(request):
    if request.method == 'POST':
        text = request.POST['todoInput']
        new_todo = Todo(todo_text=text)
        new_todo.save()
    return HttpResponseRedirect(reverse('todo_app:index'))


def delete(request, todo_id):
    todo = get_object_or_404(Todo, id=todo_id)
    todo.delete()
    return HttpResponseRedirect(reverse('todo_app:index'))


def markdone(request, todo_id):
    todo = get_object_or_404(Todo, id=todo_id)
    todo.completed = not todo.completed
    todo.save()
    return HttpResponseRedirect(reverse('todo_app:index'))

Full_Stack/django/todo_project/todosite/todo_app/templates/todo_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Todo List</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'todo_app/css/style.css' %}" />
</head>
<body>
    <div id="app">
        <div class="holder">
            <h1>Todos</h1>
            <form action="{% url 'todo_app:add' %}" method="post">
                {% csrf_token %}
                <input type="text" name="todoInput"/>
                <button type="submit">+</button>
            </form>

            <ul>
                {% for todo_item in todos %}
                <li>
                    <!--todo_id gets passed as a path parameter in todo_app.urls -->
                    <!-- views.delete now has access to <int:todo_id> -->
                    <a href="{% url 'todo_app:delete'  todo_id=todo_item.id%}">
                        <button>X</button>
                    </a>

                    <a href="{% url 'todo_app:markdone'  todo_id=todo_item.id%}">
                        <button>✓</button>
                    </a>

                    <!--same code as the a link above-->
                    <!--<form action="{% url 'todo_app:delete' todo_id=todo_item.id %}" method="post">-->
                        <!--{% csrf_token %}-->
                        <!--<button type="submit" class="delete_todo">X</button>-->
                    <!--</form>-->

                    <p {% if todo_item.completed %}
                         class="completed"
                       {% endif %} >
                        {{ todo_item.todo_text }}
                    </p>

                    <p>Completed: {{ todo_item.completed }}</p>
                    <p>Created on: {{ todo_item.created_date }}</p>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>