Full_Stack/django/library_project/library_site/library_app/urls.py
from django.urls import path
from . import views

app_name = 'library_app'  # for namespacing
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('checkin/<int:book_id>/<str:username>', views.checkin, name='checkin'),
    path('checkout/<int:book_id>/<str:username>', views.checkout, name='checkout'),
]

Full_Stack/django/library_project/library_site/library_site/urls.py
from django.contrib import admin
from django.urls import path, include
from library_site import views

urlpatterns = [
    path('library/', include('library_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register'),
]

Full_Stack/django/library_project/library_site/library_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateField('date published')
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    checked_out = models.BooleanField(default=False)
    checkout_time = models.DateTimeField(null=True, blank=True)
    checkin_time = models.DateTimeField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

Full_Stack/django/library_project/library_site/library_app/forms.py
from django import forms


class BookForm(forms.Form):
    title = forms.CharField(label='Title', max_length=100, required=False)
    pub_date = forms.DateTimeField(label='Date Published', required=False)
    author = forms.CharField(label='Author', max_length=100, required=False)

Full_Stack/django/library_project/library_site/library_app/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from .forms import BookForm
from .models import Book, Author, User
from django.contrib.auth.decorators import login_required
from django.utils import timezone


@login_required
def index(request):
    book_list = []
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            pub_date = form.cleaned_data['pub_date']
            author_name = form.cleaned_data['author']
            if author_name:
                author = get_object_or_404(Author, name=author_name)

            if not title and not pub_date and not author_name:
                book_list = Book.objects.all()
            elif title and pub_date and author_name:
                book_list = Book.objects.all().filter(title__icontains=title, pub_date=pub_date, author=author)
            elif title and pub_date:
                book_list = Book.objects.all().filter(title__icontains=title, pub_date=pub_date)
            elif title and author_name:
                book_list = Book.objects.all().filter(title__icontains=title, author=author)
            elif pub_date and author_name:
                book_list = Book.objects.all().filter(pub_date=pub_date, author=author)
            elif title:
                book_list = Book.objects.all().filter(title__icontains=title)
            elif pub_date:
                book_list = Book.objects.all().filter(pub_date=pub_date)
            elif author_name:
                book_list = Book.objects.all().filter(author=author)

            form = BookForm()  # blank form
        # if the form is invalid, we just send it back to the template
    else:
        form = BookForm()
    return render(request, 'library_app/index.html', {'form': form, 'book_list': book_list})


@login_required
def checkin(request, book_id, username):
    user = get_object_or_404(User, username=username)
    book = get_object_or_404(Book, id=book_id)
    user.book_set.remove(book)
    user.book = None
    user.save()
    book.checked_out = False
    book.checkin_time = timezone.now()
    book.save()
    return HttpResponse(f'Checked in book: {book.title}')


@login_required
def checkout(request, book_id, username):
    user = get_object_or_404(User, username=username)
    book = get_object_or_404(Book, id=book_id)
    book.checked_out = True
    book.checkout_time = timezone.now()
    user.book_set.add(book)
    user.save()
    book.save()
    return HttpResponse(f'Checked out book: {book.title}')


@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    user_books = user.book_set.all()
    return render(request, 'library_app/profile.html', {'user_books': user_books})

Full_Stack/django/library_project/library_site/library_site/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.clean_password2()
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
            return redirect('library_app:index')
        else:
            return HttpResponse('Invalid form')
    context = {
        'form': UserCreationForm()
    }
    return render(request, 'registration/register.html', context)

Full_Stack/django/library_project/library_site/library_app/templates/library_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Library</title>
</head>
<body>
<h1>Welcome {{ user.username }}</h1>
<a href="{% url 'library_app:profile' user.username %}">Click to view your profile</a>
<a href="{% url 'logout' %}">Logout</a>
<h1>Library</h1>
<form action="{% url 'library_app:index' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Search"/>
</form>
<ul>
    {% for book in book_list %}
        <li>
            {% if book.checked_out %}
                <a href="{% url 'library_app:checkin' book.id user.username %}">
                    <button>Check In</button>
                </a>
                <button disabled>Check Out</button>
            {% else %}
                <button disabled>Check In</button>
                <a href="{% url 'library_app:checkout' book.id user.username %}">
                    <button>Check Out</button>
                </a>
            {% endif %}
            <p>Title: {{ book.title }}</p>
            <p>Date Published: {{ book.pub_date }}</p>
            <p>Author: {{ book.author }}</p>
        </li>
    {% endfor %}
</ul>

</body>
</html>

Full_Stack/django/library_project/library_site/library_app/templates/library_app/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Library Profile</title>
</head>
<body>
    <h1>Books you've borrowed</h1>
    <ul>
        {%  for book in user_books %}
            <li>
                <p>Book: {{  book.title }}</p>
                <p>Author: {{  book.author }}</p>
                <p>Checked Out On: {{  book.checkout_time }}</p>
            </li>
        {%  endfor %}
    </ul>
    <a href="{% url 'library_app:index' %}">Back to library</a>
</body>
</html>

Full_Stack/django/library_project/library_site/templates/base_generic.html
<!DOCTYPE html>
<html>
<head>
    <title>
        Library | {% block title %}{% endblock title %}
    </title>
    {% block styles %}{% endblock styles %}
    {% block scripts %}{% endblock scripts %}
</head>
<body>

{% block content %}
{% endblock content %}

{% block body_scripts %}{% endblock body_scripts %}
</body>
</html>