Full_Stack/django/blog_project/blog_site/blog_app/urls.py
from django.urls import path
from . import views


app_name = 'blog_app'  # for namespacing
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('make_post/', views.make_post, name='make_post'),
    path('post_detail/<str:blog_id>', views.post_detail, name='post_detail'),
    path('make_comment/<str:blog_id>', views.make_comment, name='make_comment'),
]

Full_Stack/django/blog_project/blog_site/blog_site/urls.py
from django.contrib import admin
from django.urls import path, include
from blog_site import views

urlpatterns = [
    path('blog/', include('blog_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register'),
]

Full_Stack/django/blog_project/blog_site/blog_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class BlogPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=100)
    body = models.TextField(max_length=None)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=True)
    blogpost = models.ForeignKey(BlogPost, on_delete=models.CASCADE, null=True, blank=True)
    body = models.TextField(max_length=None)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body

Full_Stack/django/blog_project/blog_site/blog_app/forms.py
from django import forms


class MakePostForm(forms.Form):
    title = forms.CharField(label='Title', max_length=100, required=True)
    body = forms.CharField(label='Body', widget=forms.Textarea(), required=True)


class MakeCommentForm(forms.Form):
    body = forms.CharField(label='Comment', widget=forms.Textarea(), required=False)

Full_Stack/django/blog_project/blog_site/blog_app/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from .forms import MakePostForm, MakeCommentForm
from .models import BlogPost, Comment


# Create your views here.
@login_required
def post_list(request):
    blogs_list = BlogPost.objects.all()
    return render(request, 'blog_app/post_list.html', {'blogs_list': blogs_list})


@login_required
@permission_required('blog_app.add_blogpost')
def make_post(request):
    if request.method == 'POST':
        form = MakePostForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            body = form.cleaned_data['body']
            blog_post = BlogPost(user=request.user, title=title, body=body)
            blog_post.save()
            return redirect('blog_app:post_list')
    else:
        form = MakePostForm()

    return render(request, 'blog_app/make_post.html', {'form': form})


@login_required
def post_detail(request, blog_id):
    blog = get_object_or_404(BlogPost, id=blog_id)
    form = MakeCommentForm()
    return render(request, 'blog_app/post_detail.html', {'form': form, 'blog': blog})


@login_required
def make_comment(request, blog_id):
    blog = get_object_or_404(BlogPost, id=blog_id)
    if request.method == 'POST':
        form = MakeCommentForm(request.POST)
        if form.is_valid():
            comment_text = form.cleaned_data['body']
            comment = Comment(user=request.user, blogpost=blog, body=comment_text)
            comment.save()
    else:
        form = MakeCommentForm()

    return render(request, 'blog_app/post_detail.html', {'form': form, 'blog': blog})

Full_Stack/django/blog_project/blog_site/blog_site/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User, Group, Permission
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.clean_password2()
            user = authenticate(username=username, password=password)
            group = Group.objects.get(name='commenters')
            user.groups.add(group)
            user.save()
            if user:
                login(request, user)
            return redirect('blog_app:index')
        else:
            return HttpResponse('Invalid form')
    context = {
        'form': UserCreationForm()
    }
    return render(request, 'registration/register.html', context)

Full_Stack/django/blog_project/blog_site/blog_app/templates/blog_app/make_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Blog: Make Post</title>
</head>
<body>
<h1>Welcome {{ user.username }}</h1>
<a href="{% url 'blog_app:post_list' %}">Back to blogs list</a>
<h1>Make A Post</h1>
<form action="{% url 'blog_app:make_post' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit"/>
</form>
</body>
</html>

Full_Stack/django/blog_project/blog_site/blog_app/templates/blog_app/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Blog</title>
</head>
<body>
<h1>Welcome {{ user.username }}</h1>
<a href="{% url 'blog_app:post_list' %}">Back to blogs list</a>
<p>Title: {{  blog.title }}</p>
<p>User: {{ blog.user.username }}</p>
<p>Timestamp: {{  blog.timestamp }}</p>
<p>Body: {{  blog.body }}</p>
<ul>
    {% for comment in blog.comment_set.all %}
    <li>
        <p>User: {{ comment.user.username }}</p>
        <p>Time: {{ comment.timestamp }}</p>
        <p>Comment: {{ comment.body }}</p>
    </li>
    {% endfor %}
</ul>
<form action="{% url 'blog_app:make_comment' blog.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit"/>
</form>
</body>
</html>

Full_Stack/django/blog_project/blog_site/blog_app/templates/blog_app/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Blog</title>
</head>
<body>
<h1>Welcome {{ user.username }}</h1>
<a href="{% url 'blog_app:make_post' %}">Make a post</a>
<a href="{% url 'logout' %}">Logout</a>
<h1>Blogs</h1>
<ul>
    {% for blog in blogs_list %}
        <li>
            <a href="{% url 'blog_app:post_detail' blog.id %}">Title: {{  blog.title }}</a>
            <p>User: {{ blog.user.username }}</p>
            <p>Timestamp: {{  blog.timestamp }}</p>
        </li>
    {% endfor %}
</ul>
</body>
</html>

Full_Stack/django/blog_project/blog_site/templates/base_generic.html
<!DOCTYPE html>
<html>
<head>
    <title>
        Blog | {% block title %}{% endblock title %}
    </title>
    {% block styles %}{% endblock styles %}
    {% block scripts %}{% endblock scripts %}
</head>
<body>

{% block content %}
{% endblock content %}

{% block body_scripts %}{% endblock body_scripts %}
</body>
</html>